#below addtions are for hos
- type: loadout
  id: UniformHeadSecurityThong
  equipment:
    jumpsuit: ClothingUniformHeadSecurityThong

- type: loadout
  id: HandsHeadSecurityWarmers
  equipment:
    gloves: ClothingHandsHeadSecurityWarmers

- type: loadout
  id: UnderSocksHeadSecurity
  equipment:
    shoes: ClothingUnderSocksHeadSecurity

#pdas
- type: loadout
  id: HoSPDA
  equipment:
    id: HoSPDA

- type: loadout
  id: ChiefOfSecurityPDA
  equipment:
    id: ChiefOfSecurityPDA

- type: loadout
  id: SecurityDirectorPDA
  equipment:
    id: SecurityDirectorPDA

- type: loadout
  id: SheriffPDA
  equipment:
    id: SheriffPDA
