- type: job
  id: ChiefJustice
  name: job-name-chief-justice
  description: job-description-chief-justice
  playTimeTracker: JobChiefJustice
  requirements:
    - !type:RoleTimeRequirement # Floofstation - detla-v disabled but we want our CJ to have clerk time
      role: JobClerk
      time: 5h # Floofstatoin - lowering the time requirement from 10 to 5 hours becuase clerk is one job slot
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 10h
    - !type:RoleTimeRequirement
      role: JobProsecutor
      time: 10h
    - !type:OverallPlaytimeRequirement
      time: 25h
  weight: 20
  startingGear: CJGear
  icon: "JobIconChiefJustice"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  whitelisted: false # floofstation - we don't want CJ to be whitelisted like delta-v had it
  access:
  - Command
  - ChiefJustice
  - Justice
  - Lawyer
  - Prosecutor
  - Clerk
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: CJGear
  equipment:
    #jumpsuit: ClothingUniformJumpsuitChiefJustice
    #back: ClothingBackpackFilled # TODO- make Justice department bags
    #shoes: ClothingShoesLeather
    #head: ClothingHeadHatCJToque
    #outerClothing: ClothingOuterChiefJustice
    #id: ChiefJusticePDA # Floofstation - let loadouts handle what pda to give
    ears: ClothingHeadsetAltJustice
    #gloves: ClothingHandsGlovesColorWhite
    # Todo - pocket1: Gavel
    #innerClothingSkirt: ClothingUniformJumpskirtChiefJustice
    #satchel: ClothingBackpackSatchelFilled # TODO- make Justice departmebt bags
    #duffelbag: ClothingBackpackDuffelFilled

- type: chameleonOutfit
  id: ChiefJusticeChameleonOutfit
  job: ChiefJustice
  hasMindShield: true
  equipment:
    id: ChiefJusticePDA
    ears: ClothingHeadsetAltJustice
    head: ClothingHeadHatCJToque
    jumpsuit: ClothingUniformJumpsuitChiefJustice
    outerClothing: ClothingOuterChiefJustice
    shoes: ClothingShoesLeather
